# Generated by Django 5.2.16 on 2026-08-02 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', help_text='Primary email address.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number (any format — normalized in Phase 6).', max_length=50)),
                ('job_title', models.CharField(blank=True, default='', help_text='Job title (normalized in Phase 6: Sr.→Senior, Eng.→Engineer).', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('quality_score', models.IntegerField(default=0, help_text='0–100 quality score. Higher = more complete and verified.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normalized_email', models.CharField(blank=True, db_index=True, default='', help_text='Lowercased, stripped email. Used for deduplication in Phase 6.', max_length=254)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, default='', help_text='E.164 format phone. Used for deduplication in Phase 6.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete — inactive contacts excluded from normal queries.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['organization', 'last_name', 'first_name'], name='idx_contacts_org_name')],
            },
        ),
    ]
