# Generated by Django 5.2.16 on 2026-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['quality_score'], name='idx_contacts_quality'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'created_at'], name='idx_contacts_org_created'),
        ),
    ]
