# Generated by Django 5.2.16 on 2026-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_idx_contacts_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='LinkedIn profile URL.', max_length=500),
        ),
    ]
