# Generated by Django 5.2.16 on 2026-08-02 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_idx_contacts_quality_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicatePair',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.IntegerField(help_text='0-100 confidence score that these are duplicates.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detection_level', models.CharField(help_text='e.g. L1_EXACT_EMAIL, L2_EXACT_PHONE, L3_NAME_COMPANY', max_length=50)),
                ('resolved', models.BooleanField(default=False, help_text='Has a user manually reviewed and merged/dismissed this pair?')),
                ('contact_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_as_a', to='contacts.contact')),
                ('contact_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_as_b', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Duplicate Pair',
                'verbose_name_plural': 'Duplicate Pairs',
                'db_table': 'duplicate_pairs',
                'ordering': ['-confidence'],
                'unique_together': {('contact_a', 'contact_b')},
            },
        ),
    ]
