# Generated by Django 5.1.4 on 2026-08-01 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Full organization name, e.g. 'Acme Corporation'", max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'acme-corporation'. Must be unique.", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive organizations cannot log in or access data.')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
