# Generated by Django 5.2.16 on 2026-08-02 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company legal or trade name.', max_length=255)),
                ('domain', models.CharField(blank=True, default='', help_text="Primary email domain, e.g. 'acme.com'. Used for deduplication.", max_length=255)),
                ('industry', models.CharField(blank=True, default='', help_text="Industry sector, e.g. 'Technology', 'Healthcare'.", max_length=100)),
                ('website', models.URLField(blank=True, default='', help_text='Company website URL.', max_length=500)),
                ('phone', models.CharField(blank=True, default='', help_text='Main company phone number.', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('STARTUP', '1–10 employees'), ('SMALL', '11–50 employees'), ('SMB', '51–200 employees'), ('MID_MARKET', '201–1000 employees'), ('ENTERPRISE', '1000+ employees')], default='', help_text='Company size bucket.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete — inactive companies are hidden from normal queries.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_company_name_per_org')],
            },
        ),
    ]
