# Generated by Django 5.2.16 on 2026-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', help_text='AI-generated or manual company description.'),
        ),
    ]
